### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by fmorency** [liftedinit/many-ghostcloud#1]
As a user, I want to be able to create/import an account on the website like Alberto/Gwen.

- [x] Web3Auth social login (Google, Twitter, GitHub)
- [x] Email
- [x] Seed Phrase
- [x] PEM File (import only)
- [x] Ability to log out

The Web3Auth/Email/Seed Phrase should result in the same MANY id as on Alberto and Gwen.

The decentralized web hosting backend does NOT support HSM accounts at the moment; no need to support it.

**Comment by fmorency** [comment]
@nblenke I still need to test this but I don't know how.

**Comment by fmorency** [comment]
Ok! For some reason, I don't see the login page when deployed locally (maybe a browser cache issue...?) but I was able to log in when deployed elsewhere!

I tested `Web3Auth` Google login and it worked. We still need to test `Email` and add support for `Seed Phrase` and `PEM File`

**Comment by fmorency** [comment]
I added another item to the checklist of this ticket: the ability to log out and log back in under a different identity.

**Comment by nblenke** [comment]
> Ok! For some reason, I don't see the login page when deployed locally (maybe a browser cache issue...?) but I was able to log in when deployed elsewhere!
> 
> I tested `Web3Auth` Google login and it worked. We still need to test `Email` and add support for `Seed Phrase` and `PEM File`

That's odd, i see the login area on the /dashboard route when I run locally. I've tested email as well and that seems to work.

**Comment by nblenke** [comment]
Would you happen to have an example of logging out? I'm reviewing the web3auth docs but it looks like the implementation in alberto and gwen is a bit more customized and not super intuitive.

**Comment by fmorency** [comment]
I don't. We don't use logout in our other products. Instead, we keep a list of active accounts and we can switch from one another using the account menu.

**Comment by fmorency** [comment]
Fixed by #19
