### ISSUE TITLE
Display MANY address of current account

### ISSUE THREAD

**Issue by fmorency** [liftedinit/many-ghostcloud#14]
As a user, I want to see my MANY address displayed when logged in to verify that the system uses the correct identity.

**Comment by nblenke** [comment]
Is this the MANY address?
<img width="165" alt="Screen Shot 2023-09-05 at 6 09 00 PM" src="https://github.com/liftedinit/ghostcloud/assets/649166/7771e1d9-904d-481c-a45d-72bcdd002d50">

**Comment by fmorency** [comment]
> Is this the MANY address? <img alt="Screen Shot 2023-09-05 at 6 09 00 PM" width="165" src="https://private-user-images.githubusercontent.com/649166/265837157-7771e1d9-904d-481c-a45d-72bcdd002d50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE2OTQwMDY1MTAsIm5iZiI6MTY5NDAwNjIxMCwicGF0aCI6Ii82NDkxNjYvMjY1ODM3MTU3LTc3NzFlMWQ5LTkwNGQtNDgxYy1hNDVkLTcyYmNkZDAwMmQ1MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMwOTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMDkwNlQxMzE2NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03N2E0NmVmODQ4ZWM5OTAyMzI1MzQxZmVhYjFmMGFjZWY3NWMyMzBkMzg5NThjODAyMDMxMzhkNzgzZjY2OWEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HjXfzFZK6IZXMiKr3aFt2QtSAS9pRRvbV26G7H-t4Xw">

Correct!

**Comment by nblenke** [comment]
I've included this in the account menu

**Comment by fmorency** [comment]
Fixed by #19
