### ISSUE TITLE
Instruction on how to use the website

### ISSUE THREAD

**Issue by fmorency** [liftedinit/many-ghostcloud#32]
As a user, I need clear, step-by-step instructions on initiating a deployment to eliminate any guesswork or errors, e.g., it is not clear that the archive file must contain `index.html` at the root. I also require readily accessible troubleshooting guidance and information on deployment prerequisites to ensure a smooth and efficient process.

The instructions must be on the website, i.e., some websites have (skippable) interactive tutorials on first login. While that would be super cool, it is overkill at this stage of the project unless easy to do.

**Comment by nblenke** [comment]
I'm thinking that a tooltip for each field may suffice here? If it gets lengthy we could show a popover. Here's some ideas for the content:

Many Address
A unique address associated with your account that identfies you within the many network.

Site Name
The randomly generated identifier for your deployment.

Site Description
A description for your deployment. This must be between 0-500 characters in length.

Transaction Memo
A string associated with a transaction in Web3

Dropzone
Select a zip file less that 5MB in size which contains your site build. This archive must contain an index.html file in the root.

**Comment by fmorency** [comment]
Sounds like a plan!
