### ISSUE TITLE
Deployments are removed after editing

### ISSUE THREAD

**Issue by nblenke** [liftedinit/many-ghostcloud#40]
**Describe the bug**

After updating a deployment, the item is removed from the deployments list

**To Reproduce**
1. Navigate to https://ghostcloud.org/ and log in
2. Choose to edit a deployment and click "Save"
3. See that the deployment has been removed

**Expected behavior**
Deployments should remain after editing

https://github.com/liftedinit/ghostcloud/assets/649166/6f123cdb-d877-48d7-998d-8ae26f210509

**Comment by nblenke** [comment]
@fmorency This functionality seems to be working fine locally on latest ghostcloud/many-rs main. Any ideas why we would see this on prod but not local?

**Comment by fmorency** [comment]
> @fmorency This functionality seems to be working fine locally on latest ghostcloud/many-rs main. Any ideas why we would see this on prod but not local?

Does it work in a private window on prod? Maybe a browser cache issue?

**Comment by nblenke** [comment]
Same experience in incognito

**Comment by fmorency** [comment]
I can reproduce it on production as well...

The only difference between local and prod is that local does not use any blockchain backend.

@nblenke, my deployment got deleted from the backend, not just the front end. Is that what you're seeing as well?

Edit: I re-created my deployment and now I see a dupe in the backend. Not sure what's going on... but we have an iffy node in prod. I'll investigate.

**Comment by fmorency** [comment]
I tested https://github.com/liftedinit/many-rs/pull/416 against GhostCloud `main` and everything looks fine.

@jgryffindor please deploy a testnet with https://github.com/liftedinit/many-rs/pull/416 and GC main.

**Comment by fmorency** [comment]
Fixed in https://github.com/liftedinit/ghostcloud
