### ISSUE TITLE
Deleted deployment not removed until after refresh

### ISSUE THREAD

**Issue by nblenke** [liftedinit/many-ghostcloud#41]
**Describe the bug**
After attempting to delete a deployment, the deployment is not removed until after page refresh

**To Reproduce**

1. Navigate to https://ghostcloud.org/ and log in
2. Choose to delete a deployment and click "Yes"
3. See that the deployment is not removed
4. Refresh and log in, see that the deployment is not shown

**Expected behavior**
Deleting a deployment should delete that deployment

Uploading Screen Recording 2023-10-22 at 2.27.53 PM.mov…

**Comment by nblenke** [comment]
An update here, the item does eventually get removed but there is a 10 - 20 second delay. We should disable the row actions and show a loading indicator while this is in process. This will prevent users from clicking delete too many times.

**Comment by fmorency** [comment]
> An update here, the item does eventually get removed but there is a 10 - 20 second delay. We should disable the row actions and show a loading indicator while this is in process. This will prevent users from clicking delete too many times.

Interesting, that's about the time it takes for a block to get created.

**Comment by fmorency** [comment]
Fixed by #43
