### ISSUE TITLE
As a user, I should not be able to add two deployments with the same custom domain

### ISSUE THREAD

**Issue by nblenke** [liftedinit/many-ghostcloud#42]
**Is your feature request related to a problem? Please describe.**
I should not be able to add two deployments with the same custom domain

**Describe the solution you'd like**
We should show a warning when creating a deployment if the user attempts to use an existing domain

**Additional context**
<img width="340" alt="Screen Shot 2023-10-23 at 7 41 13 PM" src="https://github.com/liftedinit/ghostcloud/assets/649166/ea8253f8-e29a-4bfc-9576-b432c01001e3">

**Comment by fmorency** [comment]
I will add a check in the backend.

**Comment by fmorency** [comment]
PR https://github.com/liftedinit/many-rs/pull/417 should prevent this issue from happening again.

**Comment by fmorency** [comment]
To be verified in https://github.com/liftedinit/ghostcloud
